# Generated by Django 5.2.1 on 2025-09-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
