# Generated by Django 5.2.1 on 2025-09-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_otp_block_until_user_otp_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_sent_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
