import os
import django
from django.conf import settings

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from django.db import connection

# Create the through table for Cart.items ManyToMany
with connection.cursor() as cursor:
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS "store_cart_items" (
            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "cart_id" bigint NOT NULL,
            "item_id" bigint NOT NULL
        );
    ''')
    cursor.execute('''
        ALTER TABLE "store_cart_items" ADD CONSTRAINT "store_cart_items_cart_id_item_id_d8fe2bdc_uniq" UNIQUE ("cart_id", "item_id");
    ''')
    cursor.execute('''
        ALTER TABLE "store_cart_items" ADD CONSTRAINT "store_cart_items_cart_id_868ad063_fk_store_cart_id" FOREIGN KEY ("cart_id") REFERENCES "store_cart" ("id") DEFERRABLE INITIALLY DEFERRED;
    ''')
    cursor.execute('''
        ALTER TABLE "store_cart_items" ADD CONSTRAINT "store_cart_items_item_id_0e2a5c11_fk_store_item_id" FOREIGN KEY ("item_id") REFERENCES "store_item" ("id") DEFERRABLE INITIALLY DEFERRED;
    ''')
    cursor.execute('''
        CREATE INDEX "store_cart_items_cart_id_868ad063" ON "store_cart_items" ("cart_id");
    ''')
    cursor.execute('''
        CREATE INDEX "store_cart_items_item_id_0e2a5c11" ON "store_cart_items" ("item_id");
    ''')

print("Table created successfully")
