# Generated by Django 5.2.1 on 2025-09-03 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.CharField(max_length=20, null=True)),
                ('image', models.URLField(null=True)),
                ('icon', models.CharField(max_length=25, null=True)),
                ('color', models.CharField(max_length=25, null=True)),
                ('popular_brands', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=200)),
                ('item_type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('image_urls', models.JSONField(blank=True, default=list, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='store.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.seller')),
            ],
            options={
                'indexes': [models.Index(fields=['seller', 'is_active'], name='store_item_seller__5a8f23_idx'), models.Index(fields=['category', 'is_active'], name='store_item_categor_29a3a6_idx'), models.Index(fields=['item_name', 'is_active'], name='store_item_item_na_b3bbdd_idx')],
            },
        ),
    ]
