# Generated by Django 5.2.1 on 2025-09-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
