# Generated by Django 5.2.1 on 2025-09-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='accounts.seller'),
        ),
    ]
