# Generated by Django 5.2.1 on 2025-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_savedforlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderuser',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
