# Generated by Django 5.2.1 on 2025-09-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='referral_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
